# Generated by Django 5.1.6 on 2025-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='puntuaje',
        ),
        migrations.AddField(
            model_name='desafio',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
