# Generated by Django 5.1.6 on 2025-02-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_profile_image'),
    ]

    operations = [
    ]
