# Generated by Django 5.1.6 on 2025-02-25 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_formulariocontacto_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='desafios_likeados', to=settings.AUTH_USER_MODEL),
        ),
    ]
