# Generated by Django 5.1.6 on 2025-02-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_publicacion_likes_publicacion_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='contenido',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comentariopublicacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.publicacion'),
        ),
    ]
