# Generated by Django 5.1.6 on 2025-02-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_comentariopublicacion_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursosdidacticos',
            name='nombre',
            field=models.CharField(default='Default Resource', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recursosdidacticos',
            name='tipo',
            field=models.CharField(choices=[('teoria', 'Teoría'), ('pista', 'Pista')], default='teoria', max_length=10),
        ),
        migrations.AlterField(
            model_name='recursosdidacticos',
            name='url_contenido',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
