# Generated by Django 5.1.6 on 2025-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recursosdidacticos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosdidacticos',
            name='nombre',
            field=models.CharField(default='Recurso sin nombre', max_length=100),
        ),
    ]
