# Generated by Django 5.1.6 on 2025-02-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_recursosdidacticos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='clave_cifrado',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='codigo_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='entrada_usuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='enunciado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='intentos_maximos',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='desafio',
            name='lenguaje_programacion',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('Otros', 'Otros')], default='Otros', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='pistas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='query_vulnerable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='recursos_afectados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='ruta_vulnerable',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='solucion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='texto_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='tiempo_limite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desafio',
            name='tipo_cifrado',
            field=models.CharField(blank=True, choices=[('ROT13', 'ROT13'), ('César', 'César'), ('AES', 'AES'), ('Base64', 'Base64'), ('SHA256', 'SHA256'), ('Otros', 'Otros')], default='Otros', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='tipo_dos',
            field=models.CharField(blank=True, choices=[('HTTP Flood', 'HTTP Flood'), ('SYN Flood', 'SYN Flood'), ('Amplificación', 'Amplificación'), ('Otros', 'Otros')], default='Otros', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='token_requerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desafio',
            name='url_vulnerable',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='valor_correcto',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='variable_manipulada',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='nivel_dificultad',
            field=models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado'), ('Experto', 'Experto')], default='Principiante', max_length=64),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='tematica',
            field=models.CharField(choices=[('Cifrado', 'Cifrado'), ('XSS', 'XSS'), ('Inyección SQL', 'Inyección SQL'), ('Ejecución de Código', 'Ejecución de Código'), ('Path Traversal', 'Path Traversal'), ('Denegación de Servicio', 'Denegación de Servicio'), ('Manipulación de Estado del Cliente', 'Manipulación de Estado del Cliente'), ('XSRF', 'XSRF'), ('XSSI', 'XSSI'), ('Vulnerabilidades de Configuración', 'Vulnerabilidades de Configuración'), ('Ajax', 'Ajax'), ('Otros', 'Otros')], default='Otros', max_length=64),
        ),
    ]
