# Generated by Django 5.1.6 on 2025-02-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_desafio_clave_cifrado_desafio_codigo_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='codigo_base',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='entrada_usuario',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='intentos_maximos',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='lenguaje_programacion',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='pistas',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='query_vulnerable',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='recursos_afectados',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='ruta_vulnerable',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='tiempo_limite',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='tipo_dos',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='token_requerido',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='url_vulnerable',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='valor_correcto',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='variable_manipulada',
        ),
    ]
