# Generated by Django 5.1.6 on 2025-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usuariodesafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursosdidacticos',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
