# Generated by Django 5.1.6 on 2025-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_recursosdidacticos_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
