# Generated by Django 4.2.9 on 2025-03-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_profile_is2fa_enabled_profile_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='tematica',
            field=models.CharField(choices=[('Cifrado', 'Cifrado'), ('XSS', 'XSS'), ('Inyección SQL', 'Inyección SQL'), ('Ejecución de Código', 'Ejecución de Código'), ('Path Traversal', 'Path Traversal'), ('Denegación de Servicio', 'Denegación de Servicio'), ('Manipulación de Estado del Cliente', 'Manipulación de Estado del Cliente'), ('XSRF', 'XSRF'), ('XSSI', 'XSSI'), ('Vulnerabilidades de Configuración', 'Vulnerabilidades de Configuración'), ('Ajax', 'Ajax'), ('Depuración ', 'Depuración ')], default='Otros', max_length=64),
        ),
    ]
