# Generated by Django 5.1.7 on 2025-03-11 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_desafio_tematica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('imagen_bloqueada', models.URLField(max_length=500)),
                ('imagen_desbloqueada', models.URLField(max_length=500)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('fecha_obtenido', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trofeos', to='api.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trofeos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
