# Generated by Django 5.1.7 on 2025-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_trofeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trofeo',
            name='imagen_bloqueada',
            field=models.ImageField(blank=True, null=True, upload_to='trofeos/'),
        ),
        migrations.AlterField(
            model_name='trofeo',
            name='imagen_desbloqueada',
            field=models.ImageField(blank=True, null=True, upload_to='trofeos/'),
        ),
    ]
