# Generated by Django 5.1.7 on 2025-03-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_trofeo_nombre_alter_trofeo_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='trofeos_desbloqueables',
            field=models.ManyToManyField(blank=True, related_name='desafios_asociados', to='api.trofeo'),
        ),
    ]
