# Generated by Django 5.1.7 on 2025-03-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_desafio_trofeos_desbloqueables'),
    ]

    operations = [
        migrations.AddField(
            model_name='trofeo',
            name='nivel_requerido',
            field=models.IntegerField(default=0),
        ),
    ]
