# Generated by Django 5.1.7 on 2025-03-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_trofeo_nivel_requerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='trofeo',
            name='desbloqueo_por_nivel',
            field=models.BooleanField(default=False),
        ),
    ]
