# Generated by Django 5.1.7 on 2025-03-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_trofeo_desbloqueo_por_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trofeo',
            name='desafios_desbloqueantes',
            field=models.ManyToManyField(blank=True, related_name='desafios_desbloqueantes', to='api.desafio'),
        ),
    ]
