# Generated by Django 5.1.7 on 2025-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_trofeo_desbloqueo_por_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trofeo',
            name='desbloqueo_por_nivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trofeo',
            name='nivel_requerido',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
