# Generated by Django 5.1.7 on 2025-03-12 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_trofeo_desbloqueo_por_nivel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trofeo',
            name='user',
        ),
        migrations.AddField(
            model_name='trofeo',
            name='usuarios_desbloqueados',
            field=models.ManyToManyField(blank=True, related_name='trofeos_desbloqueados', to=settings.AUTH_USER_MODEL),
        ),
    ]
