# Generated by Django 5.1.7 on 2025-03-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_trofeo_user_trofeo_usuarios_desbloqueados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trofeo',
            name='profile',
        ),
    ]
