# Generated by Django 5.1.7 on 2025-03-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_trofeo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trofeo',
            name='desbloqueado',
        ),
    ]
