# Generated by Django 5.1.7 on 2025-03-16 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_trofeo_desbloqueado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trofeo',
            name='usuarios_notificados',
            field=models.ManyToManyField(blank=True, related_name='trofeos_notificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
