# Generated by Django 5.1.7 on 2025-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_trofeo_usuarios_notificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trofeo',
            name='imagen_bloqueada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trofeo',
            name='imagen_desbloqueada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
